### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by koiseka** [Muirey03/BrickFix#2]
Date: 2019-07-09 05:56:42 +0000
Process: SpringBoard
Bundle id: com.apple.springboard
Exception type: NSInvalidArgumentException
Reason: -[SBMainSwitcherViewController mediaServerDiedNotification:]: unrecognized selector sent to instance 0x103858800
Culprit: BrickFix.dylib
Device: iPhone XR, iOS 12.1.2
Call stack:
0 CoreFoundation 0x00000001ffb4ff68 __exceptionPreprocess
1 libobjc.A.dylib 0x00000001fed4c284 objc_exception_throw
2 CoreFoundation 0x00000001ffa650e0 -[NSOrderedSet initWithSet:copyItems:]
3 UIKitCore 0x000000022d83b1ec -[UIResponder doesNotRecognizeSelector:]
4 BrickFix.dylib 0x00000001035f7dd4 BrickFix.dylib + 15828
5 CoreFoundation 0x00000001ffb559bc ___forwarding___
6 CoreFoundation 0x00000001ffb57730 _CF_forwarding_prep_0
7 Foundation 0x00000002005ec618 __57-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_2
8 CoreFoundation 0x00000001ffabc19c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
9 CoreFoundation 0x00000001ffabc15c ___CFXRegistrationPost_block_invoke
10 CoreFoundation 0x00000001ffabb604 _CFXRegistrationPost
11 CoreFoundation 0x00000001ffabb290 ___CFXNotificationPost_block_invoke
12 CoreFoundation 0x00000001ffa30cb4 -[_CFXNotificationRegistrar find:object:observer:enumerator:]
13 CoreFoundation 0x00000001ffabad14 _CFXNotificationPost
14 Foundation 0x00000002004d9b24 -[NSNotificationCenter postNotificationName:object:userInfo:]
15 ImageCorrect.dylib 0x0000000108063444 ImageCorrect.dylib + 29764
16 ImageCorrect.dylib 0x00000001080634e0 ImageCorrect.dylib + 29920
17 Celestial 0x000000020582e6f0 figConnection_ServerConnectionDied_Callback
18 CoreFoundation 0x00000001ffabbaac __CFNotificationCenterAddObserver_block_invoke
19 CoreFoundation 0x00000001ffabc19c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
20 CoreFoundation 0x00000001ffabc15c ___CFXRegistrationPost_block_invoke
21 CoreFoundation 0x00000001ffabb604 _CFXRegistrationPost
22 CoreFoundation 0x00000001ffabb290 ___CFXNotificationPost_block_invoke
23 CoreFoundation 0x00000001ffa30cb4 -[_CFXNotificationRegistrar find:object:observer:enumerator:]
24 CoreFoundation 0x00000001ffabad14 _CFXNotificationPost
25 CoreFoundation 0x00000001ffabbc98 CFNotificationCenterPostNotificationWithOptions
26 CoreMedia 0x00000002031728fc CMNotificationCenterPostNotification
27 CoreMedia 0x0000000203172b58 fncCallOriginalCallbackAndReleaseWeakListener
28 CoreMedia 0x00000002031725e4 fncHandleWeakNotification
29 CoreFoundation 0x00000001ffabbaac __CFNotificationCenterAddObserver_block_invoke
30 CoreFoundation 0x00000001ffabc19c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
31 CoreFoundation 0x00000001ffabc15c ___CFXRegistrationPost_block_invoke
32 CoreFoundation 0x00000001ffabb604 _CFXRegistrationPost
33 CoreFoundation 0x00000001ffabb290 ___CFXNotificationPost_block_invoke
34 CoreFoundation 0x00000001ffa30cb4 -[_CFXNotificationRegistrar find:object:observer:enumerator:]
35 CoreFoundation 0x00000001ffabad14 _CFXNotificationPost
36 CoreFoundation 0x00000001ffabbc98 CFNotificationCenterPostNotificationWithOptions
37 CoreMedia 0x00000002031728fc CMNotificationCenterPostNotification
38 CoreMedia 0x0000000203294be4 figXPC_PostDeferredServerNotification
39 CoreMedia 0x0000000203173a48 figDeferredNotificationDispatchFunction
40 libdispatch.dylib 0x00000001ff5552f0 _dispatch_client_callout
41 libdispatch.dylib 0x00000001ff55c6e0 _dispatch_lane_serial_drain
42 libdispatch.dylib 0x00000001ff55d264 _dispatch_lane_invoke
43 libdispatch.dylib 0x00000001ff5640d4 _dispatch_root_queue_drain
44 libdispatch.dylib 0x00000001ff563e7c _dispatch_worker_thread
45 libsystem_pthread.dylib 0x00000001ff753974 _pthread_body
46 libsystem_pthread.dylib 0x00000001ff7538d0 _pthread_start
47 libsystem_pthread.dylib 0x00000001ff75bddc thread_start

**Comment by Muirey03** [comment]
Fixed in v.1.0.1
